# Admin User Login /admin/auth/login
sandbox_admin_api_auth_login:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminUserLoginController.php"
    type:     annotation
    prefix:   /auth

# Admin User Logout /admin/auth/logout
sandbox_admin_api_auth_logout:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminUserLogoutController.php"
    type:     annotation
    prefix:   /auth

# products recommend /admin/products/recommend
sandbox_admin_api_products_recommend:
    resource: "@SandboxAdminApiBundle/Controller/Product/AdminProductRecommendController.php"
    type:     annotation
    prefix:   /

# products appointments /admin/products/{id}/appointments
sandbox_admin_api_products_appoinments:
    resource: "@SandboxAdminApiBundle/Controller/Product/AdminProductAppointmentController.php"
    type:     annotation
    prefix:   /

# products /admin/products
sandbox_admin_api_products:
    resource: "@SandboxAdminApiBundle/Controller/Product/AdminProductController.php"
    type:     annotation
    prefix:   /

# Orders /admin/orders
sandbox_admin_api_orders:
    resource: "@SandboxAdminApiBundle/Controller/Order/AdminOrderController.php"
    type:     annotation
    prefix:   /

# Rooms /admin/rooms/attachments
sandbox_admin_api_rooms_attachments:
    resource: "@SandboxAdminApiBundle/Controller/Room/AdminRoomAttachmentController.php"
    type:     annotation
    prefix:   /

# Rooms /admin/rooms/supplies
sandbox_admin_api_rooms_supplies:
    resource: "@SandboxAdminApiBundle/Controller/Room/AdminRoomSuppliesController.php"
    type:     annotation
    prefix:   /

# Rooms /admin/rooms
sandbox_admin_api_rooms:
    resource: "@SandboxAdminApiBundle/Controller/Room/AdminRoomController.php"
    type:     annotation
    prefix:   /

# Announcement /admin/announcements
sandbox_admin_api_announcements:
    resource: "@SandboxAdminApiBundle/Controller/Announcement/AdminAnnouncementController.php"
    type:     annotation
    prefix:   /

# Door /admin/doors
sandbox_admin_api_doors:
    resource: "@SandboxAdminApiBundle/Controller/Door/AdminDoorController.php"
    type:     annotation
    prefix:   /

# Admins /admin/admins
sandbox_admin_api_admins:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminAdminsController.php"
    type:     annotation
    prefix:   /

# User /admin/users
sandbox_admin_api_users:
    resource: "@SandboxAdminApiBundle/Controller/User/AdminUsersController.php"
    type:     annotation
    prefix:   /

# User /admin/permissions
sandbox_admin_api_permissions:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminPermissionsController.php"
    type:     annotation
    prefix:   /

# Admin Token Auth /admin/auth/me
sandbox_admin_api_auth:
    resource: "@SandboxAdminApiBundle/Controller/Auth/AdminAuthController.php"
    type:     annotation
    prefix:   /auth

# Events /admin/events/orders
sandbox_admin_api_event_orders:
    resource: "@SandboxAdminApiBundle/Controller/Event/AdminEventOrderController.php"
    type:     annotation
    prefix:  /

# Events /admin/events/{id}/comments
sandbox_admin_api_event_comments:
    resource: "@SandboxAdminApiBundle/Controller/Event/AdminEventCommentController.php"
    type:     annotation
    prefix:  /

# Events registrations /admin/events/{event-id}/registrations
sandbox_admin_api_events_registrations:
    resource: "@SandboxAdminApiBundle/Controller/Event/AdminEventRegistrationController.php"
    type:     annotation
    prefix:  /

# Events /admin/events
sandbox_admin_api_events:
    resource: "@SandboxAdminApiBundle/Controller/Event/AdminEventController.php"
    type:     annotation
    prefix:  /

# Banner Tags /admin/banner/tags
sandbox_admin_api_banner_tags:
    resource: "@SandboxAdminApiBundle/Controller/Banner/AdminBannerTagController.php"
    type:     annotation
    prefix:   /

# Banners /admin/banners
sandbox_admin_api_banners:
    resource: "@SandboxAdminApiBundle/Controller/Banner/AdminBannerController.php"
    type:     annotation
    prefix:   /

# News /admin/news
sandbox_admin_api_news:
    resource: "@SandboxAdminApiBundle/Controller/News/AdminNewsController.php"
    type:     annotation
    prefix:   /

# Message /admin/messages
sandbox_admin_api_message:
    resource: "@SandboxAdminApiBundle/Controller/Message/AdminMessageController.php"
    type:     annotation
    prefix:   /

# MessagePush /admin/push/messages
sandbox_admin_api_message_push:
    resource: "@SandboxAdminApiBundle/Controller/Message/AdminMessagePushController.php"
    type:     annotation
    prefix:   /

# Room Building /admin/building
sandbox_admin_api_building:
    resource: "@SandboxAdminApiBundle/Controller/Building/AdminBuildingController.php"
    type:     annotation
    prefix:   /

# Verify Feed /admin/verify/feeds
sandbox_admin_api_verify_feed:
    resource: "@SandboxAdminApiBundle/Controller/Verify/AdminVerifyFeedController.php"
    type:     annotation
    prefix:   /verify

#Verify Company /admin/verify/companies
sandbox_admin_api_verify_company:
    resource: "@SandboxAdminApiBundle/Controller/Verify/AdminVerifyCompanyController.php"
    type:     annotation
    prefix:   /verify

# Payment /admin/payment
sandbox_admin_api_payment:
    resource: "@SandboxAdminApiBundle/Controller/Payment/AdminPaymentController.php"
    type:     annotation
    prefix:   /

# SalesAdmin /admin/sales/admins
sandbox_admin_api_sales_admins:
    resource: "@SandboxAdminApiBundle/Controller/SalesAdmin/AdminSalesCompanyController.php"
    type:     annotation
    prefix:   /sales

# SalesBuilding /admin/sales/buildings
sandbox_admin_api_sales_buildings:
    resource: "@SandboxAdminApiBundle/Controller/SalesAdmin/AdminSalesBuildingController.php"
    type:     annotation
    prefix:   /sales

# ShopAdmin /admin/shop/admins
sandbox_admin_api_shop_admins:
    resource: "@SandboxAdminApiBundle/Controller/SalesAdmin/AdminShopAdminsController.php"
    type:     annotation
    prefix:   /shop

# SalesCity /admin/sales/{id}/cities
sandbox_admin_api_sales_cities:
    resource: "@SandboxAdminApiBundle/Controller/SalesAdmin/AdminSalesCityController.php"
    type:     annotation
    prefix:   /sales

# Shop /admin/shops
sandbox_admin_api_shops:
    resource: "@SandboxAdminApiBundle/Controller/Shop/AdminShopController.php"
    type:     annotation
    prefix:   /

# ShopOrder /admin/shop/orders
sandbox_admin_api_shop_orders:
    resource: "@SandboxAdminApiBundle/Controller/Shop/AdminShopOrderController.php"
    type:     annotation
    prefix:   /

# Bulletin Type /admin/bulletins/type
sandbox_admin_api_bulletins_type:
    resource: "@SandboxAdminApiBundle/Controller/Bulletin/AdminBulletinTypeController.php"
    type:     annotation
    prefix:   /

# Bulletin /admin/bulletins
sandbox_admin_api_bulletins:
    resource: "@SandboxAdminApiBundle/Controller/Bulletin/AdminBulletinPostController.php"
    type:     annotation
    prefix:   /

# Logs /admin/logs
sandbox_admin_api_logs:
    resource: "@SandboxAdminApiBundle/Controller/Log/AdminLogController.php"
    type:     annotation
    prefix:   /

# Advertising /admin/advertising
sandbox_admin_api_advertising:
    resource: "@SandboxAdminApiBundle/Controller/Advertising/AdminAdvertisingController.php"
    type:     annotation
    prefix:   /

# Dashboard /admin/dashboard
sandbox_admin_api_dashboard:
    resource: "@SandboxAdminApiBundle/Controller/DashBoard/AdminDashBoardController.php"
    type:     annotation
    prefix:   /

# Position /admin/position
sandbox_admin_api_position:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminPositionController.php"
    type:     annotation
    prefix:   /

# Position Binding /admin/position/binding
sandbox_admin_api_position_binding:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminPositionBindingController.php"
    type:     annotation
    prefix:   /

sandbox_admin_api_platform_set:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminPlatformController.php"
    type:     annotation
    prefix:   /

# Evaluation /admin/evaluation
sandbox_admin_api_evaluation:
    resource: "@SandboxAdminApiBundle/Controller/Evaluation/AdminEvaluationController.php"
    type:     annotation
    prefix:   /

# TopUpOrder /admin/topup/orders
sandbox_admin_api_topup_orders:
    resource: "@SandboxAdminApiBundle/Controller/Order/AdminTopUpOrderController.php"
    type:     annotation
    prefix:   /

# Space /admin/space
sandbox_admin_api_space:
    resource: "@SandboxAdminApiBundle/Controller/Space/AdminCommunityController.php"
    type:     annotation
    prefix:   /space

# Lease Bill /admin/leases/bills
sandbox_admin_api_lease_bill:
    resource: "@SandboxAdminApiBundle/Controller/Lease/AdminLeaseBillController.php"
    type:     annotation
    prefix:   /

# Lease /admin/leases
sandbox_admin_api_leases:
    resource: "@SandboxAdminApiBundle/Controller/Lease/AdminLeaseController.php"
    type:     annotation
    prefix:   /

# Location /admin/location
sandbox_admin_api_location:
    resource: "@SandboxAdminApiBundle/Controller/Location/AdminLocationController.php"
    type:     annotation
    prefix:   /

# User Profile
sandbox_amin_api_user_profile:
    resource: "@SandboxAdminApiBundle/Controller/User/AdminUserProfileController.php"
    type:     annotation
    prefix:   /

# Admin Finance
sandbox_admin_finance_api:
    resource: "@SandboxAdminApiBundle/Resources/config/finance/routing.yml"
    type: rest
    prefix: /

# Membership Card Order
sandbox_admin_api_membership_card_order:
    resource: "@SandboxAdminApiBundle/Controller/MembershipCard/AdminMembershipCardOrderController.php"
    type:     annotation
    prefix:   /