# Admin User Login /admin/auth/login
sandbox_admin_api_auth_login:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminUserLoginController.php"
    type:     annotation
    prefix:   /auth

# Rooms /admin/rooms/attachments
sandbox_admin_api_rooms_attachments:
    resource: "@SandboxAdminApiBundle/Controller/Room/AdminRoomAttachmentController.php"
    type:     annotation
    prefix:   /

# Rooms /admin/rooms
sandbox_admin_api_rooms:
    resource: "@SandboxAdminApiBundle/Controller/Room/AdminRoomController.php"
    type:     annotation
    prefix:   /

# Announcement /admin/announcements
sandbox_admin_api_announcements:
    resource: "@SandboxAdminApiBundle/Controller/Announcement/AdminAnnouncementController.php"
    type:     annotation
    prefix:   /
