# Admin User Login /admin/auth/login
sandbox_admin_api_auth_login:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminUserLoginController.php"
    type:     annotation
    prefix:   /auth

# Admin User Logout /admin/auth/logout
sandbox_admin_api_auth_logout:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminUserLogoutController.php"
    type:     annotation
    prefix:   /auth

# products /admin/products
sandbox_admin_api_products:
    resource: "@SandboxAdminApiBundle/Controller/Product/AdminProductController.php"
    type:     annotation
    prefix:   /

# products recommend /admin/products/recommend
sandbox_admin_api_products_recommend:
    resource: "@SandboxAdminApiBundle/Controller/Product/AdminProductRecommendController.php"
    type:     annotation
    prefix:   /

# Orders /admin/orders
sandbox_admin_api_orders:
    resource: "@SandboxAdminApiBundle/Controller/Order/AdminOrderController.php"
    type:     annotation
    prefix:   /

# Rooms /admin/rooms/attachments
sandbox_admin_api_rooms_attachments:
    resource: "@SandboxAdminApiBundle/Controller/Room/AdminRoomAttachmentController.php"
    type:     annotation
    prefix:   /

# Rooms /admin/rooms/supplies
sandbox_admin_api_rooms_supplies:
    resource: "@SandboxAdminApiBundle/Controller/Room/AdminRoomSuppliesController.php"
    type:     annotation
    prefix:   /

# Rooms /admin/rooms
sandbox_admin_api_rooms:
    resource: "@SandboxAdminApiBundle/Controller/Room/AdminRoomController.php"
    type:     annotation
    prefix:   /

# Announcement /admin/announcements
sandbox_admin_api_announcements:
    resource: "@SandboxAdminApiBundle/Controller/Announcement/AdminAnnouncementController.php"
    type:     annotation
    prefix:   /

# Door /admin/doors
sandbox_admin_api_doors:
    resource: "@SandboxAdminApiBundle/Controller/Door/AdminDoorController.php"
    type:     annotation
    prefix:   /

# Admins /admin/admins
sandbox_admin_api_admins:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminAdminsController.php"
    type:     annotation
    prefix:   /

# User /admin/users
sandbox_admin_api_users:
    resource: "@SandboxAdminApiBundle/Controller/User/AdminUsersController.php"
    type:     annotation
    prefix:   /

# User /admin/users
sandbox_admin_api_types:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminTypesController.php"
    type:     annotation
    prefix:   /

# User /admin/permissions
sandbox_admin_api_permissions:
    resource: "@SandboxAdminApiBundle/Controller/Admin/AdminPermissionsController.php"
    type:     annotation
    prefix:   /

# Admin Token Auth /admin/auth/me
sandbox_admin_api_auth:
    resource: "@SandboxAdminApiBundle/Controller/Auth/AdminAuthController.php"
    type:     annotation
    prefix:   /auth

