<?php

namespace Sandbox\ApiBundle\Repository\Banner;

use Doctrine\ORM\EntityRepository;
use Sandbox\AdminApiBundle\Data\Banner\BannerPosition;
use Sandbox\ApiBundle\Entity\Banner\Banner;

/**
 * BannerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
    /**
     * Get banner list.
     *
     * @param string $search
     *
     * @return array
     */
    public function getAdminBannerList(
        $search = null
    ) {
        $query = $this->createQueryBuilder('b')
            ->orderBy('b.sortTime', 'DESC');

        // search by
        if (!is_null($search)) {
            $query = $query->where('b.title LIKE :search OR b.content LIKE :search')
                ->setParameter('search', '%'.$search.'%');
        }

        $query = $query->getQuery()->getResult();

        return $query;
    }

    /**
     * Get banner list.
     *
     * @param string $search
     *
     * @return array
     */
    public function getClientBannerList(
        $search = null
    ) {
        $query = $this->createQueryBuilder('b')
            ->where('b.source != :blank_block')
            ->orderBy('b.sortTime', 'DESC')
            ->setParameter('blank_block', Banner::SOURCE_BLANK_BLOCK);

        // search by
        if (!is_null($search)) {
            $query = $query->where('b.title LIKE :search OR b.content LIKE :search')
                ->setParameter('search', '%'.$search.'%');
        }

        $query = $query->getQuery()->getResult();

        return $query;
    }

    /**
     * @param string $sortTime
     * @param string $action
     *
     * @return mixed
     */
    public function findSwapBanner(
        $sortTime,
        $action
    ) {
        // operator and order direction
        $operator = '>';
        $direction = 'ASC';
        if ($action == BannerPosition::ACTION_DOWN) {
            $operator = '<';
            $direction = 'DESC';
        }

        $query = $this->createQueryBuilder('b')
            ->where('b.sortTime '.$operator.' :sortTime')
            ->setParameter('sortTime', $sortTime)
            ->orderBy('b.sortTime', $direction)
            ->setMaxResults(1)
            ->getQuery();

        return $query->getSingleResult();
    }

    /**
     * @param $limit
     * @param $offset
     *
     * @return array
     */
    public function getLimitList(
        $limit,
        $offset
    ) {
        $query = $this->createQueryBuilder('b')
                ->setFirstResult($offset)
                ->setMaxResults($limit)
                ->orderBy('b.sortTime', 'DESC')
                ->getQuery();

        $result = $query->getResult();

        return $result;
    }
}
