<?php

namespace Sandbox\ApiBundle\Repository\Banner;

use Doctrine\ORM\EntityRepository;

/**
 * BannerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
    /**
     * Get banner list.
     *
     * @param string $search
     *
     * @return array
     */
    public function getBannerList(
        $search = null
    ) {
        $query = $this->createQueryBuilder('b')
            ->orderBy('b.sortTime', 'DESC');

        // search by
        if (!is_null($search)) {
            $query = $query->andWhere('b.title LIKE :search OR b.content LIKE :search')
                ->setParameter('search', '%'.$search.'%');
        }

        $query = $query->getQuery()->getResult();

        return $query;
    }
}
