<?php

namespace Sandbox\ApiBundle\Repository\Banner;

use Doctrine\ORM\EntityRepository;
use Sandbox\AdminApiBundle\Data\Banner\BannerPosition;
use Sandbox\ApiBundle\Entity\Banner\CommnueBanner;

/**
 * CommnueBannerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommnueBannerRepository extends EntityRepository
{
    /**
     * Get Commnue_banner list.
     *
     * @param string $search
     *
     * @return array
     */
    public function getAdminBannerList(
        $search = null
    ) {
        $query = $this->createQueryBuilder('cb')
            ->orderBy('cb.sortTime', 'DESC');

        // search by
        if (!is_null($search)) {
            $query = $query->where('cb.title LIKE :search OR cb.content LIKE :search')
                ->setParameter('search', '%'.$search.'%');
        }

        $query = $query->getQuery()->getResult();

        return $query;
    }

    /**
     * @param string $sortTime
     * @param string $action
     *
     * @return mixed
     */
    public function findSwapBanner(
        $sortTime,
        $action
    ) {
        // operator and order direction
        $operator = '>';
        $direction = 'ASC';
        if ($action == BannerPosition::ACTION_DOWN) {
            $operator = '<';
            $direction = 'DESC';
        }

        $query = $this->createQueryBuilder('cb')
            ->where('cb.sortTime '.$operator.' :sortTime')
            ->setParameter('sortTime', $sortTime)
            ->orderBy('cb.sortTime', $direction)
            ->setMaxResults(1)
            ->getQuery();

        return $query->getSingleResult();
    }
}