<?php

namespace Sandbox\ApiBundle\Repository\Admin;

use Doctrine\ORM\EntityRepository;

/**
 * AdminPermissionGroupRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminPermissionGroupRepository extends EntityRepository
{
    /**
     * @param $adminId
     * @param $platform
     * @param $salesCompanyId
     *
     * @return array
     */
    public function getMyPermissionGroups(
        $adminId,
        $platform,
        $salesCompanyId
    ) {
        $positionBindingsQuery = $this->getEntityManager()->createQueryBuilder()
            ->select('DISTINCT pb.positionId')
            ->from('SandboxApiBundle:Admin\AdminPositionUserBinding', 'pb')
            ->leftJoin('pb.position', 'p')
            ->where('pb.userId = :adminId')
            ->andWhere('p.platform = :platform')
            ->setParameter('adminId', $adminId)
            ->setParameter('platform', $platform);

        if (!is_null($salesCompanyId)) {
            $positionBindingsQuery->andWhere('p.salesCompanyId = :company')
                ->setParameter('company', $salesCompanyId);
        }

        $positions = $positionBindingsQuery->getQuery()->getResult();
        $positionIds = array_map('current', $positions);

        $excludeGroupIds = $this->getExcludeGroupIds(
            $platform,
            $salesCompanyId
        );

        $groupBindingsQuery = $this->getEntityManager()->createQueryBuilder()
            ->select('
                gr.id,
                gr.groupKey as key,
                gr.groupName as name
            ')
            ->from('SandboxApiBundle:Admin\AdminPositionGroupBinding', 'pgb')
            ->leftJoin('pgb.position', 'p')
            ->leftJoin('pgb.group', 'gr')
            ->where('p.id IN (:positionIds)')
            ->groupBy('gr.id')
            ->setParameter('positionIds', $positionIds);

        if (!empty($excludeGroupIds)) {
            $groupBindingsQuery->andWhere('gr.id NOT IN (:ids)')
                ->setParameter('ids', $excludeGroupIds);
        }

        return $groupBindingsQuery->getQuery()->getResult();
    }

    /**
     * @param $platform
     * @param $salesCompanyId
     *
     * @return array
     */
    public function getPermissionGroupByPlatform(
        $platform,
        $salesCompanyId
    ) {
        $excludeGroupIds = $this->getExcludeGroupIds(
            $platform,
            $salesCompanyId
        );

        $query = $this->createQueryBuilder('g')
            ->select('
                g.id,
                g.groupKey as key,
                g.groupName as name
            ')
            ->where('g.platform = :platform')
            ->setParameter('platform', $platform);

        if (!empty($excludeGroupIds)) {
            $query->andWhere('g.id NOT IN (:ids)')
                ->setParameter('ids', $excludeGroupIds);
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @param $platform
     * @param $salesCompanyId
     *
     * @return array
     */
    private function getExcludeGroupIds(
        $platform,
        $salesCompanyId
    ) {
        $excludeGroupIdsQuery = $this->getEntityManager()->createQueryBuilder()
            ->select('ep.groupId')
            ->from('SandboxApiBundle:Admin\AdminExcludePermission', 'ep')
            ->where('ep.platform = :platform')
            ->andWhere('ep.groupId IS NOT NULL')
            ->setParameter('platform', $platform);

        if (!is_null($salesCompanyId)) {
            $excludeGroupIdsQuery
                ->andWhere('(ep.salesCompanyId = :salesCompanyId OR ep.salesCompanyId IS NULL)')
                ->setParameter('salesCompanyId', $salesCompanyId);
        }

        $excludeGroupIds = array_map('current', $excludeGroupIdsQuery->getQuery()->getResult());

        return $excludeGroupIds;
    }
}
