<?php

namespace Sandbox\ApiBundle\Repository\Material;

use Doctrine\ORM\EntityRepository;
use Sandbox\ApiBundle\Entity\Material\CommnueMaterial;

/**
 * CommnueMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommnueMaterialRepository extends EntityRepository
{
    public function getCategory()
    {
        $query = $this->createQueryBuilder('cm')
            ->select('cm.category');

        return $query->getQuery()->getResult();
    }
}
