<?php

namespace Sandbox\ApiBundle\Repository\Material;

use Doctrine\ORM\EntityRepository;
use Sandbox\ApiBundle\Entity\Material\CommnueMaterial;

/**
 * CommnueMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommnueMaterialRepository extends EntityRepository
{
}
