# Orders /orders
sandbox_api_order:
    resource: "@SandboxApiBundle/Controller/Order/OrderController.php"
    type:     annotation
    prefix:   /

# Products /products
sandbox_api_product:
    resource: "@SandboxApiBundle/Controller/Product/ProductController.php"
    type:     annotation
    prefix:   /


# Location
sandbox_api_location:
    resource: "@SandboxApiBundle/Controller/Location/LocationController.php"
    type:     annotation
    prefix:   /location

# Payment
sandbox_api_payment:
    resource: "@SandboxApiBundle/Controller/Payment/PaymentController.php"
    type:     annotation
    prefix:   /


# MembershipOrder
sandbox_api_membership_order:
    resource: "@SandboxApiBundle/Controller/Order/MembershipOrderController.php"
    type:     annotation
    prefix:   /

# MembershipOrder
sandbox_api_topup_order:
    resource: "@SandboxApiBundle/Controller/Order/TopUpOrderController.php"
    type:     annotation
    prefix:   /