# FEEDS/feeds
sandbox_api_feed:
    resource: "@SandboxApiBundle/Controller/FeedController.php"
    type:     rest

sandbox_api_feed_like:
    resource: "@SandboxApiBundle/Controller/FeedLikeController.php"
    type:     rest
    parent:   sandbox_api_feed

sandbox_api_feed_comment:
    resource: "@SandboxApiBundle/Controller/FeedCommentController.php"
    type:     rest
    parent:   sandbox_api_feed

# COMPANIES /companies
sandbox_api_company:
    resource: "@SandboxApiBundle/Controller/CompanyController.php"
    type:     rest

sandbox_api_company_member:
    resource: "@SandboxApiBundle/Controller/CompanyMemberController.php"
    type:     rest
    parent:   sandbox_api_company

# DIRECTORIES /directories
sandbox_api_directory:
    resource: "@SandboxApiBundle/Controller/DirectoryController.php"
    type:     rest

# VCARDS /vcards
sandbox_api_vcard:
    resource: "@SandboxApiBundle/Controller/VcardController.php"
    type:     rest

# Login /login
sandbox_api_login:
    resource: "@SandboxApiBundle/Controller/LoginController.php"
    type:     annotation
    prefix:   /

# Bind email /email
sandbox_api_email_bind:
    resource: "@SandboxApiBundle/Controller/EmailBindingController.php"
    type:     annotation
    prefix:   /

# Bind phone /phone
sandbox_api_phone_bind:
    resource: "@SandboxApiBundle/Controller/PhoneBindingController.php"
    type:     annotation
    prefix:   /

# Registration /register
sandbox_api_registration:
    resource: "@SandboxApiBundle/Controller/RegistrationController.php"
    type:     annotation
    prefix:   /

# Password /password
sandbox_api_password:
    resource: "@SandboxApiBundle/Controller/PasswordController.php"
    type:     annotation
    prefix:   /
