# Location /location
sandbox_api_location:
    resource: "@SandboxApiBundle/Controller/Location/LocationController.php"
    type:     annotation
    prefix:   /location

# Payment
sandbox_api_payment:
    resource: "@SandboxApiBundle/Controller/Payment/PaymentController.php"
    type:     annotation
    prefix:   /

# User Hobby /user/hobbies
sandbox_api_user_hobby:
    resource: "@SandboxApiBundle/Controller/User/UserHobbyController.php"
    type:     rest
    prefix:   /user
