# Location /location
sandbox_api_location:
    resource: "@SandboxApiBundle/Controller/Location/LocationController.php"
    type:     annotation
    prefix:   /location

# User Hobby /user/hobbies
sandbox_api_user_hobby:
    resource: "@SandboxApiBundle/Controller/User/UserHobbyController.php"
    type:     rest
    prefix:   /user

# Payment
sandbox_api_payment:
    resource: "@SandboxApiBundle/Controller/Payment/PaymentController.php"
    type:     annotation
    prefix:   /

# MembershipOrder
sandbox_api_membership_order:
    resource: "@SandboxApiBundle/Controller/Order/MembershipOrderController.php"
    type:     annotation
    prefix:   /

# MembershipOrder
sandbox_api_topup_order:
    resource: "@SandboxApiBundle/Controller/Order/TopUpOrderController.php"
    type:     annotation
    prefix:   /

# Company Industry /company/industries
sandbox_api_company_industries:
    resource: "@SandboxApiBundle/Controller/Company/CompanyIndustryController.php"
    type:     annotation
    prefix:   /company

# Food /food
sandbox_api_food:
    resource: "@SandboxApiBundle/Controller/Food/FoodController.php"
    type:     annotation
    prefix:   /

# APP Info /apps
sandbox_api_app:
    resource: "@SandboxApiBundle/Controller/App/AppController.php"
    type:     annotation
    prefix:   /

# UserProfile
sandbox_api_user profile:
    resource: "@SandboxApiBundle/Controller/User/UserProfileController.php"
    type:     annotation
    prefix:   /