# Shopping Cart /frontdesk
sandbox_api_frontdesk:
    resource: "@SandboxApiBundle/Controller/Shop/ShopCartController.php"
    type:     annotation
    prefix:   /frontdesk

# Location /location
sandbox_api_location:
    resource: "@SandboxApiBundle/Controller/Location/LocationController.php"
    type:     annotation
    prefix:   /location

# User Hobby /user/hobbies
sandbox_api_user_hobby:
    resource: "@SandboxApiBundle/Controller/User/UserHobbyController.php"
    type:     rest
    prefix:   /user

# Payment
sandbox_api_payment:
    resource: "@SandboxApiBundle/Controller/Payment/PaymentController.php"
    type:     annotation
    prefix:   /

# MembershipOrder
sandbox_api_membership_order:
    resource: "@SandboxApiBundle/Controller/Order/MembershipOrderController.php"
    type:     annotation
    prefix:   /

# MembershipOrder
sandbox_api_topup_order:
    resource: "@SandboxApiBundle/Controller/Order/TopUpOrderController.php"
    type:     annotation
    prefix:   /

# Company Industry /company/industries
sandbox_api_company_industries:
    resource: "@SandboxApiBundle/Controller/Company/CompanyIndustryController.php"
    type:     annotation
    prefix:   /company

# Food /food
sandbox_api_food:
    resource: "@SandboxApiBundle/Controller/Food/FoodController.php"
    type:     annotation
    prefix:   /

# APP Info /apps
sandbox_api_app:
    resource: "@SandboxApiBundle/Controller/App/AppController.php"
    type:     annotation
    prefix:   /

# UserProfile
sandbox_api_user profile:
    resource: "@SandboxApiBundle/Controller/User/UserProfileController.php"
    type:     annotation
    prefix:   /

# Feature Info /features
sandbox_api_features:
    resource: "@SandboxApiBundle/Controller/Feature/FeatureController.php"
    type:     annotation
    prefix:   /

# Menu Info /menus
sandbox_api_menus:
    resource: "@SandboxApiBundle/Controller/Menu/MenuController.php"
    type:     annotation
    prefix:   /

# Open Server /openserver/users
sandbox_api_openserver_user:
    resource: "@SandboxApiBundle/Controller/Server/OpenServerUserController.php"
    type:     annotation
    prefix:   /

# Open Server /openserver/client/login
sandbox_api_openserver_auth_login:
    resource: "@SandboxApiBundle/Controller/Server/OpenServerUserLoginController.php"
    type:     annotation
    prefix:   /

# WeChat Share /wechat/share/signature
sandbox_api_wechat_share_signature:
    resource: "@SandboxApiBundle/Controller/ThirdParty/WeChatShareController.php"
    type:     annotation
    prefix:   /

# User Phone Code /user/phonecode/lists
sandbox_api_user_phone_code:
    resource: "@SandboxApiBundle/Controller/User/UserPhoneCodeController.php"
    type:     annotation
    prefix:   /

# Bulletin /bulletins
sandbox_api_bulletins:
    resource: "@SandboxApiBundle/Controller/Bulletin/BulletinController.php"
    type:     annotation
    prefix:   /

# RoomTypes /rooms
sandbox_api_rooms:
    resource: "@SandboxApiBundle/Controller/Room/RoomController.php"
    type:     annotation
    prefix:   /rooms

# Logs
sandbox_api_logs:
    resource: "@SandboxApiBundle/Controller/Log/LogController.php"
    type:     annotation
    prefix:   /

# FileServer
sandbox_api_file_server:
    resource: "@SandboxApiBundle/Controller/FileServer/FileServerController.php"
    type:     annotation
    prefix:   /

# Building /building
sandbox_api_building:
    resource: "@SandboxApiBundle/Controller/Building/BuildingController.php"
    type:     annotation
    prefix:   /

# Parameter /parameter
sandbox_api_parameter:
    resource: "@SandboxApiBundle/Controller/Parameter/ParameterController.php"
    type:     annotation
    prefix:   /

# Lease Rent Types /leases/renttypes
sandbox_api_lease_rent_types:
    resource: "@SandboxApiBundle/Controller/Lease/LeaseRentTypesController.php"
    type:     annotation
    prefix:   /

# Version Check
sandbox_api_version_check:
    resource: "@SandboxApiBundle/Controller/Version/ClientVersionCheckController.php"
    type:     annotation
    prefix:   /

# Duiba
sandbox_api_duiba:
    resource: "@SandboxApiBundle/Controller/Duiba/DuibaController.php"
    type:     annotation
    prefix:   /

# Property
sandbox_api_property_types:
    resource: "@SandboxApiBundle/Controller/Property/PropertyTypeController.php"
    type:     annotation
    prefix:   /property

# Door Public
sandbox_api_door_public:
    resource: "@SandboxApiBundle/Controller/DoorV2/DoorPublicController.php"
    type:     annotation
    prefix:   /

sandbox_rpc_sample:
    resource: "@SandboxApiBundle/Controller/RpcSample/RpcSampleController.php"
    type:     annotation
    prefix:   /

sandbox_api_expert_field:
    resource: "@SandboxApiBundle/Controller/Expert/ExpertFieldController.php"
    type:     annotation
    prefix:   /