parameters:
#    sandbox_api.example.class: Sandbox\ApiBundle\Example

services:
#    sandbox_api.example:
#        class: %sandbox_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]