services:
    sandbox_api.admin_permission_check_service:
        class: Sandbox\ApiBundle\Service\AdminPermissionCheckService
        arguments: ['@service_container']
    sandbox_api.admin_platform:
        class: Sandbox\ApiBundle\Service\AdminPlatformService
        arguments: ['@service_container', '@security.token_storage']
    sandbox_api.order:
        class: Sandbox\ApiBundle\Service\OrderService
        arguments: ['@service_container']
    sandbox_api.group_user:
        class: Sandbox\ApiBundle\Service\GroupUsersService
        arguments: ['@service_container']
    sandbox_api.bean:
        class: Sandbox\ApiBundle\Service\BeanService
        arguments: ['@service_container']
    sandbox_api.admin_remark:
        class: Sandbox\ApiBundle\Service\AdminRemarkService
        arguments: ['@service_container']
    sandbox_api.sales_customer:
        class: Sandbox\ApiBundle\Service\SalesCustomerService
        arguments: ['@service_container']
    sandbox_api.admin_status_log:
        class: Sandbox\ApiBundle\Service\AdminStatusLogService
        arguments: ['@service_container']
    sandbox_api.jpush_im:
        class: Sandbox\ApiBundle\Service\JpushImService
        arguments: ['@service_container']