services:
    sandbox_api.admin_permission_check_service:
        class: Sandbox\ApiBundle\Service\AdminPermissionCheckService
        arguments: ['@service_container']
    sandbox_api.admin_platform:
        class: Sandbox\ApiBundle\Service\AdminPlatformService
        arguments: ['@service_container', '@security.token_storage']
    sandbox_api.order:
        class: Sandbox\ApiBundle\Service\OrderService
        arguments: ['@service_container']
    sandbox_api.group_user:
        class: Sandbox\ApiBundle\Service\GroupUsersService
        arguments: ['@service_container']
    sandbox_api.bean:
        class: Sandbox\ApiBundle\Service\BeanService
        arguments: ['@service_container']
    sandbox_api.admin_remark:
        class: Sandbox\ApiBundle\Service\AdminRemarkService
        arguments: ['@service_container']
    sandbox_api.sales_customer:
        class: Sandbox\ApiBundle\Service\SalesCustomerService
        arguments: ['@service_container']
    sandbox_api.admin_status_log:
        class: Sandbox\ApiBundle\Service\AdminStatusLogService
        arguments: ['@service_container']
    sandbox_api.jmessage:
        class: Sandbox\ApiBundle\Service\JmessageService
        arguments: ['@service_container']
    sandbox_api.export:
        class: Sandbox\ApiBundle\Service\AdminExportService
        arguments: ['@service_container']
    sandbox_api.sales_wallet:
        class: Sandbox\ApiBundle\Service\AdminSalesWalletService
        arguments: ['@service_container']
    sandbox_api.des_encrypt:
        class: Sandbox\ApiBundle\Service\DESencryptService
        arguments: ['@service_container']
    sandbox_api.jmessage_property:
        class: Sandbox\ApiBundle\Service\JmessagePropertyService
        arguments: ['@service_container']
    sandbox_api.jmessage_commnue:
        class: Sandbox\ApiBundle\Service\JmessageCommnueService
        arguments: ['@service_container']
    sandbox_rpc.client:
        class: Sandbox\ApiBundle\Service\RpcClient
        arguments: ['@service_container']