services:
    sandbox_api.admin_permission_check_service:
        class: Sandbox\ApiBundle\Service\AdminPermissionCheckService
        arguments: ['@service_container']
    sandbox_api.admin_platform:
        class: Sandbox\ApiBundle\Service\AdminPlatformService
        arguments: ['@service_container', '@security.token_storage']