CREATE TABLE `RoomBuilding` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(1024) DEFAULT NULL,
  `detail` LONGTEXT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `lat` FLOAT(9,6) NOT NULL,
  `lng` FLOAT(9,6) NOT NULL,
  `cityId` int(11) NOT NULL,
  `server` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `businessHour` VARCHAR(255) DEFAULT NULL,
  `visible` tinyint(1) NOT NULL,
  `companyId` int(11) NOT NULL,
  `status` enum('pending','accept','refuse','banned') NOT NULL,
  `isDeleted` tinyint(1) NOT NULL,
  `orderRemindPhones` varchar(2048) DEFAULT NULL,
  `creationDate` datetime NOT NULL,
  `modificationDate` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_Building_cityId_idx` (`cityId`),
  CONSTRAINT `fk_Building_cityId` FOREIGN KEY (`cityId`) REFERENCES `RoomCity` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
);