FROM debian:8
MAINTAINER <account@sandbox3.cn>

# Update distribution
COPY data/sources.list /etc/apt/sources.list
RUN apt-get update && apt-get upgrade -y

# Install tools
RUN apt-get install -y \
    vim \
    cron \
    nginx \
    php5-fpm \
    php5-mysql \
    php5-curl \
    php5-common \
    php5-redis \
    php5-gd \
    libxrender1 \
    fonts-wqy-zenhei \
    php5-mcrypt \
    && rm -fr /var/lib/apt/lists/*

# Copy startup script
COPY homestead/*.sh /root/
RUN chown root:root /root/*.sh && chmod +x /root/*.sh \
    && rm -rf /etc/nginx/sites-available/default

COPY homestead/sandbox.conf /etc/nginx/conf.d/sandbox.conf
COPY data/www.conf /etc/php5/fpm/pool.d/www.conf
COPY data/crontab /etc/crontab

WORKDIR /var/www
EXPOSE 80

# Run startup script
ENTRYPOINT ["/root/entrypoint.sh"]