<?php

namespace Sandbox\ApiBundle\Repository\Shop;

use Doctrine\ORM\EntityRepository;
use Sandbox\AdminShopApiBundle\Data\Shop\ShopMenuPosition;

/**
 * ShopProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopProductRepository extends EntityRepository
{
    /**
     * @param $menuId
     *
     * @return array
     */
    public function countShopProductByMenu(
        $menuId
    ) {
        $query = $this->createQueryBuilder('p')
            ->select('COUNT(p.id)')
            ->where('p.menuId = :menuId')
            ->andWhere('p.invisible = :invisible')
            ->setParameter('menuId', $menuId)
            ->setParameter('invisible', false)
            ->getQuery();

        return $query->getSingleScalarResult();
    }

    /**
     * @param $menuId
     *
     * @return array
     */
    public function getShopProductByShopId(
        $shopId,
        $id
    ) {
        $query = $this->createQueryBuilder('p')
            ->join('SandboxApiBundle:Shop\ShopMenu', 'm', 'WITH', 'm.id = p.menuId')
            ->join('SandboxApiBundle:Shop\Shop', 's', 'WITH', 's.id = m.shopId')
            ->where('p.id = :id')
            ->andWhere('s.id = :shopId')
            ->andWhere('p.invisible = :invisible')
            ->setParameter('id', $id)
            ->setParameter('invisible', false)
            ->setParameter('shopId', $shopId)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * @param $shopId
     *
     * @return array
     */
    public function getShopProductsByShopId(
        $shopId,
        $menuId = null,
        $online = null,
        $search = null
    ) {
        $query = $this->createQueryBuilder('p')
            ->join('SandboxApiBundle:Shop\ShopMenu', 'm', 'WITH', 'm.id = p.menuId')
            ->join('SandboxApiBundle:Shop\Shop', 's', 'WITH', 's.id = m.shopId')
            ->where('p.invisible = :invisible')
            ->andWhere('s.id = :shopId')
            ->setParameter('invisible', false)
            ->setParameter('shopId', $shopId);

        if (!is_null($menuId)) {
            $query = $query->andWhere('m.id = :menuId')
                ->setParameter('menuId', $menuId);
        }

        if (!is_null($online)) {
            $query = $query->andWhere('p.online = :online')
                ->setParameter('online', $online);
        }

        // Search products by product Id or product name.
        if (!is_null($search)) {
            $query->andWhere('p.id LIKE :search OR p.name LIKE :search')
                ->setParameter('search', "%$search%");
        }

        $query = $query->getQuery();

        return $query->getResult();
    }

    /**
     * @param $menuId
     * @param $limit
     * @param $offset
     *
     * @return array
     */
    public function getShopProductsByMenu(
        $menuId,
        $limit,
        $offset
    ) {
        $query = $this->createQueryBuilder('p')
            ->where('p.menuId = :menuId')
            ->andWhere('p.online = :online')
            ->andWhere('p.invisible = :invisible')
            ->setParameter('menuId', $menuId)
            ->setParameter('invisible', false)
            ->setParameter('online', true)
            ->orderBy('p.sortTime', 'DESC')
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * @param $product
     * @param $action
     *
     * @return array
     */
    public function findSwapShopProduct(
        $product,
        $action
    ) {
        $query = $this->createQueryBuilder('p')
            ->where('p.menuId = :menuId')
            ->andWhere('p.invisible = :invisible')
            ->setParameter('invisible', false)
            ->setParameter('menuId', $product->getMenuId());

        // operator
        $operator = '>';
        $orderBy = 'ASC';
        if ($action == ShopMenuPosition::ACTION_DOWN) {
            $operator = '<';
            $orderBy = 'DESC';
        }

        $query = $query->andWhere('p.sortTime '.$operator.' :sortTime')
            ->setParameter('sortTime', $product->getSortTime())
            ->orderBy('p.sortTime', $orderBy)
            ->setMaxResults(1)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
