<?php

namespace Sandbox\ApiBundle\Repository\Shop;

use Doctrine\ORM\EntityRepository;

/**
 * ShopSpecRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopSpecRepository extends EntityRepository
{
    /**
     * @param $shopId
     *
     * @return array
     */
    public function getSpecsByShop(
        $shopId
    ) {
        $query = $this->createQueryBuilder('ss')
            ->where('ss.shopId = :shopId')
            ->andWhere('ss.invisible = :invisible')
            ->andWhere('ss.auto = :auto')
            ->orderBy('ss.id', 'ASC')
            ->setParameter('shopId', $shopId)
            ->setParameter('invisible', false)
            ->setParameter('auto', false);

        return $query->getQuery()->getResult();
    }
}
