<?php

namespace Sandbox\ApiBundle\Repository\Shop;

use Doctrine\ORM\EntityRepository;

/**
 * ShopProductSpecRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopProductSpecRepository extends EntityRepository
{
    /**
     * @param $productId
     *
     * @return array
     */
    public function findRequiredSpecsByProduct(
        $productId
    ) {
        $query = $this->createQueryBuilder('s')
            ->where('s.productId = :productId')
            ->andWhere('s.optional = :optional')
            ->setParameter('productId', $productId)
            ->setParameter('optional', false)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * @param $menuId
     *
     * @return array
     */
    public function findSingleSpecsByProduct(
        $productId
    ) {
        $query = $this->createQueryBuilder('s')
            ->where('s.productId = :productId')
            ->andWhere('s.optional = :optional')
            ->setParameter('productId', $productId)
            ->setParameter('optional', false)
            ->getQuery();

        return $query->getResult();
    }
}
