<?php

namespace Sandbox\ApiBundle\Repository\Shop;

use Doctrine\ORM\EntityRepository;

/**
 * ShopRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends EntityRepository
{
    /**
     * @param $buildingId
     * @param bool|true $allowed
     *
     * @return array
     */
    public function getShopByBuilding(
        $buildingId,
        $allowed = true
    ) {
        $query = $this->createQueryBuilder('s')
            ->where('s.buildingId = :buildingId')
            ->setParameter('buildingId', $buildingId);

        // check if only can see shops currently active
        if (!$allowed) {
            $query = $query->andWhere('s.active = :active')
                ->setParameter('active', true);
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @param $shopId
     * @param bool|true $allowed
     *
     * @return array
     */
    public function getShopById(
        $shopId,
        $allowed = true
    ) {
        $query = $this->createQueryBuilder('s')
            ->where('s.id = :shopId')
            ->setParameter('shopId', $shopId);

        // check if only can see shops currently open
        if (!$allowed) {
            $query = $query->andWhere('s.active = :active')
                ->setParameter('active', true);
        }

        return $query->getQuery()->getSingleResult();
    }
}
