<?php

namespace Sandbox\ApiBundle\Repository\Shop;

use Doctrine\ORM\EntityRepository;

/**
 * ShopProductSpecItemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopProductSpecItemRepository extends EntityRepository
{
    /**
     * @param $shopId
     *
     * @return array
     */
    public function getItemsByProduct(
        $productId,
        $itemId
    ) {
        $query = $this->createQueryBuilder('i')
            ->join('SandboxApiBundle:Shop\ShopProductSpec', 's', 'WITH', 's.id = i.productSpecId')
            ->join('SandboxApiBundle:Shop\ShopProduct', 'p', 'WITH', 'p.id = s.productId')
            ->where('i.id = :itemId')
            ->andWhere('p.id = :productId')
            ->setParameter('itemId', $itemId)
            ->setParameter('productId', $productId);

        return $query->getQuery()->getOneOrNullResult();
    }
}
