<?php

namespace Sandbox\ApiBundle\Repository\Shop;

use Doctrine\ORM\EntityRepository;
use Sandbox\AdminApiBundle\Data\Shop\ShopMenuPosition;

/**
 * ShopMenuRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopMenuRepository extends EntityRepository
{
    public function findSwapShopMenu(
        $menu,
        $action
    ) {
        $query = $this->createQueryBuilder('m')
            ->where('m.shopId = :shopId')
            ->setParameter('shopId', $menu->getShopId());

        // operator
        $operator = '>';
        $orderBy = 'ASC';
        if ($action == ShopMenuPosition::ACTION_DOWN) {
            $operator = '<';
            $orderBy = 'DESC';
        }

        $query = $query->andWhere('m.sortTime '.$operator.' :sortTime')
            ->setParameter('sortTime', $menu->getSortTime())
            ->orderBy('m.sortTime', $orderBy)
            ->setMaxResults(1)
            ->getQuery();

        return $query->getResult();
    }
}
