<?php

namespace Sandbox\ApiBundle\Repository\Advertising;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertisingRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisingAttachmentRepository extends EntityRepository
{
    public function findAttachment(
        $advertising,
        $height,
        $width
    ) {
        $query = $this->createQueryBuilder('a')
            ->select('a.content')
            ->where('a.advertising = :advertising')
            ->andWhere('a.height = :height')
            ->andWhere('a.width = :width')
            ->setParameter('advertising', $advertising)
            ->setParameter('height', $height)
            ->setParameter('width', $width)
            ->getQuery();

        try {
            $result = $query->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            $result = null;
        }

        return $result;
    }
}
