<?php

namespace Sandbox\ApiBundle\Repository\Advertising;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertisingRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisingRepository extends EntityRepository
{
    public function getAdvertisingList()
    {
        $query = $this->createQueryBuilder('a')
            ->orderBy('id', 'DESC')
            ->getQuery();

        return $query;
    }
}
