<?php

namespace Sandbox\ApiBundle\Repository\Advertising;

use Doctrine\ORM\EntityRepository;

/**
 * CommnueAdvertisingMiddleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommnueAdvertisingMiddleRepository extends EntityRepository
{
}
