<?php

namespace Sandbox\ApiBundle\Repository\Advertising;

use Doctrine\ORM\EntityRepository;


/**
 * CommnueAdvertisingScreenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommnueAdvertisingScreenRepository extends EntityRepository
{
    /**
     * @param $limit
     * @return array
     */
    public function getVisibleScreens(
        $limit
    ) {
        $query = $this->createQueryBuilder('cas')
            ->where('cas.visible = TRUE')
            ->andWhere('cas.isSaved = TRUE')
            ->setMaxResults($limit);

        return $query->getQuery()->getResult();
    }
}
