<?php

namespace Sandbox\ApiBundle\Repository\Advertising;

use Doctrine\ORM\EntityRepository;
use Sandbox\CommnueAdminApiBundle\Data\Advertising\AdvertisingPosition;

/**
 * CommnueAdvertisingMicroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommnueAdvertisingMicroRepository extends EntityRepository
{
    /**
     * @param null $search
     * @return array
     */
    public function getMicroList(
        $search = null
    ) {
        $query = $this->createQueryBuilder('cam')
            ->where('1=1');


        if (!is_null($search)) {
            $query = $query->andWhere('cam.content LIKE :search')
                ->setParameter('search', '%'.$search.'%');
        }

        $query->orderBy('cam.sortTime', 'DESC');
        return $query->getQuery()->getResult();
    }

    /**
     * @param string $sortTime
     * @param string $action
     *
     * @return mixed
     */
    public function findSwapMicro(
        $sortTime,
        $action
    ) {
        // operator and order direction
        $operator = '>';
        $direction = 'ASC';
        if ($action == AdvertisingPosition::ACTION_DOWN) {
            $operator = '<';
            $direction = 'DESC';
        }

        $query = $this->createQueryBuilder('cam')
            ->where('cam.sortTime '.$operator.' :sortTime')
            ->setParameter('sortTime', $sortTime)
            ->orderBy('cam.sortTime', $direction)
            ->setMaxResults(1)
            ->getQuery();

        return $query->getSingleResult();
    }

    /**
     * @param $limit
     * @return array
     */
    public function getClientMicro(
        $limit
    ) {
        $query = $this->createQueryBuilder('cam')
            ->setMaxResults($limit)
            ->orderBy('cam.sortTime','DESC');

        return $query->getQuery()->getResult();
    }
}