<?php

namespace Sandbox\ApiBundle\Repository\Advertising;

use Doctrine\ORM\EntityRepository;


/**
 * CommnueAdvertisingScreenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommnueAdvertisingScreenRepository extends EntityRepository
{

}
