<?php

namespace Sandbox\ApiBundle\Repository\Advertising;

use Doctrine\ORM\EntityRepository;

/**
 * CommnueAdvertisingScreenAttachmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommnueScreenAttachmentRepository extends EntityRepository
{
    /**
     * @param $screen
     * @param null $height
     * @param null $width
     *
     * @return array
     */
    public function findAttachment(
        $screen,
        $height = null,
        $width = null
    ) {
        $query = $this->createQueryBuilder('csa')
            ->where('csa.screen = :screen')
            ->setParameter('screen', $screen);

        if (!is_null($height)) {
            $query->andWhere('csa.height = :height')
                    ->setParameter('height', $height);
        }

        if (!is_null($width)) {
            $query->andWhere('csa.width = :width')
                ->setParameter('width', $width);
        }

        $result = $query->getQuery()->getResult();

        return $result;
    }
}
