<?php

namespace Sandbox\ApiBundle\Repository\Advertising;

use Doctrine\ORM\EntityRepository;

/**
 * CommnueAdvertisingScreenAttachmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommnueScreenAttachmentRepository extends EntityRepository
{
    /**
     * @param $advertising
     * @param null $height
     * @param null $width
     *
     * @return array
     */
    public function findAttachment(
        $advertising,
        $height = null,
        $width = null
    ) {
        $query = $this->createQueryBuilder('a')
            ->where('a.advertising = :advertising')
            ->setParameter('advertising', $advertising);

        if (!is_null($height)) {
            $query->andWhere('a.height = :height')
                    ->setParameter('height', $height);
        }

        if (!is_null($width)) {
            $query->andWhere('a.width = :width')
                ->setParameter('width', $width);
        }

        $result = $query->getQuery()->getResult();

        return $result;
    }
}
