<?php

namespace Sandbox\ApiBundle\Repository\Food;

use Doctrine\ORM\EntityRepository;

/**
 * FoodRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodRepository extends EntityRepository
{
}
