sandbox_client_property_api_dashboard:
    resource: "@SandboxClientPropertyApiBundle/Controller/Dashboard/ClientDashBoardController.php"
    type:     annotation
    prefix:   /

sandbox_client_property_api_product:
    resource: "@SandboxClientPropertyApiBundle/Controller/Product/ClientProductController.php"
    type:     annotation
    prefix:   /
