<?php

namespace Sandbox\ApiBundle\Repository\Message;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JmessageHistoryRepository extends EntityRepository
{
    /**
     * @param $type
     * @param $targetId
     *
     * @return array
     */
    public function getFromIds(
        $type,
        $targetId
    ) {
        $query = $this->createQueryBuilder('m')
            ->select('m.fromId as from_id')
            ->where('m.targetType = :type')
            ->andWhere('m.targetId = :targetId')
            ->setParameter('type', $type)
            ->setParameter('targetId', $targetId);

        $query->orderBy('m.msgCtime', 'DESC');

        return $query->getQuery()->getResult();
    }

    public function getLastMessages(
        $fromID,
        $type
    ) {
        $query = $this->createQueryBuilder('m')
            ->where('m.targetType = :type')
            ->andWhere('m.fromId = :fromId or m.targetId = :fromId')
            ->setParameter('type', $type)
            ->setParameter('fromId', $fromID)
            ->setMaxResults(1);

        $query->orderBy('m.msgCtime', 'DESC');

        return $query->getQuery()->getOneOrNullResult();
    }
}
