<?php

namespace Sandbox\ApiBundle\Repository\Message;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageMaterialRepository extends EntityRepository
{
    /**
     * Get message list.
     *
     * @return array
     */
    public function getMessageMaterialList()
    {
        $query = $this->createQueryBuilder('m')
            ->where('m.visible = TRUE')
            ->orderBy('m.creationDate', 'DESC');

        return $query->getQuery()->getResult();
    }
}
