<?php

namespace Sandbox\ApiBundle\Repository\Message;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    /**
     * @param $platform
     * @param $limit
     * @param $offset
     *
     * @return array
     */
    public function getMessageList(
        $platform,
        $limit,
        $offset
    ) {
        $query = $this->createQueryBuilder('m')
            ->where('m.visible = TRUE')
            ->andWhere('m.platform = :platform')
            ->setParameter('platform', $platform)
            ->orderBy('m.creationDate', 'DESC');

        if (!is_null($limit) && !is_null($offset)) {
            $query->setMaxResults($limit)
                ->setFirstResult($offset);
        }

        return $query->getQuery()->getResult();
    }

    /**
     * @param $platform
     *
     * @return mixed
     */
    public function countMessage(
        $platform
    ) {
        $query = $this->createQueryBuilder('m')
            ->select('count(m.id)')
            ->where('m.visible = TRUE')
            ->andWhere('m.platform = :platform')
            ->setParameter('platform', $platform);

        return $query->getQuery()->getSingleScalarResult();
    }
}
