parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: sandbox_rest_api_db
    database_user: sandbox_rest_api
    database_password: sandbox_rest_api
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ae4f49befc969ff5feada55bcc88e3c0
    database_path: null
    pingpp_test_key: sk_test_ifjLO8GWnzn9n9abXDqDeTqH
    pingpp_live_key: sk_live_ic1rw45I839Q5jCJs56Fpm28
    pingpp_app_id: app_OCqnLKmXfD0OH80a
    load_more_limit: 20
    nearby_range_km: 100
    user_profile_default_name_prefix: 用户_
    xmpp_domain: devxmpp.sandbox3.cn
    openfire_innet_url: http://127.0.0.1:9090
    openfire_plugin_bstuser: /plugins/bstuser
    openfire_plugin_bstuser_users: /users
    openfire_plugin_bstuser_property_name_ezuser: ezuser
    openfire_plugin_bstuser_property_secret_ezuser: DB93819516EA9C8E73C0374595ED0F19
    sms_api_base_url: http://utf8.sms.webchinese.cn/?
    sms_api_uid: easylinks
    sms_api_key: 9b9c8912a0efb8bb77e6
    email_from_address: notification@ezlinx.cn
    email_from_name: EasyLinks Notification
    crm_api_url: http://devcrm.sandbox3.cn
    crm_api_client_user_account_authentication: /client/user/account/authentication
    crm_api_client_user_account_vip: /client/user/account/vip
    crm_api_client_own_account_balance: /client/user/account/balance
    door_api_username: admin
    door_api_password: admin
    door_api_login: /Login
    door_api_logout: /Logout
    door_api_get_doors: /GetDoors
    door_api_set_time: /SetTimePeriod
    door_api_get_card_record: /GetSwipeCardRecord
    door_api_get_alarm_record: /GetAlarmRecord
    door_api_set_card_permission: /SetCardPermission
    door_api_session_id: SessionId=
    door_api_begin_time: BeginTime=
    door_api_end_time: EndTime=
    door_api_time_period: TimePeriod=
    door_api_card_permission: CardPermission=
