parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: sandbox_rest_api_db
    database_user: sandbox_rest_api
    database_password: sandbox_rest_api
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ae4f49befc969ff5feada55bcc88e3c0
    database_path: null
