parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: sandbox_rest_api_db
    database_user: sandbox_rest_api
    database_password: sandbox_rest_api
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ae4f49befc969ff5feada55bcc88e3c0
    database_path: null
    pingpp_key: sk_live_j2rM2ESCjctUTaWZ7frzjNFE
    pingpp_app_id: app_TSu14S5GKGeTfDWD
    load_more_limit: 20
    nearby_range_km: 100
    expired_verification_time: +10 minutes
    user_profile_default_name_prefix: 用户_
    xmpp_domain: devxmpp.sandbox3.cn
    openfire_innet_url: http://127.0.0.1:9090
    openfire_plugin_bstuser: /plugins/bstuser
    openfire_plugin_bstuser_users: /users
    openfire_plugin_bstuser_property_name_ezuser: ezuser
    openfire_plugin_bstuser_property_secret_ezuser: DB93819516EA9C8E73C0374595ED0F19
    sms_api_base_url: http://utf8.sms.webchinese.cn/?
    sms_api_uid: account@sandbox3.cn
    sms_api_key: 807574a49cc90043531c
    email_from_address: notification@sandbox3.cn
    email_from_name: 展想创合
    sandbox_auth_key: sandbox_auth_test
    crm_api_url: http://devcrm.sandbox3.cn
    crm_api_client_user_account_authentication: /client/user/account/authentication
    crm_api_client_user_account_vip: /client/user/account/vip
    crm_api_admin_user_account_vip: /admin/useraccounts/{userId}/vip
    crm_api_admin_user_account_cardno: /admin/useraccounts/{userId}/cardno
    crm_api_client_own_account_balance: /client/user/account/balance
    crm_api_admin_user_balance_change: /admin/useraccounts/{userId}/balance/change
    crm_api_admin_user_consume: /admin/useraccounts/{userId}/consume
    crm_api_admin_user_account_upgrade: /admin/useraccounts/{userId}/upgrade
    crm_api_admin_price_rule_include: /admin/price/rule/include/{buildingId}/{roomNo}
    crm_api_admin_price_rule_exclude: /admin/price/rule/exclude/{buildingId}/{roomNo}
    crm_api_admin_user_create: /admin/useraccounts/{userId}/create
    crm_api_client_user_price_calculate: /client/user/price/rules/{rule_id}/calculate
    door_api_username: admin
    door_api_password: admin
    door_api_login: /Login
    door_api_logout: /Logout
    door_api_get_doors: /GetDoors
    door_api_set_time: /SetTimePeriod
    door_api_get_card_record: /GetSwipeCardRecord
    door_api_get_alarm_record: /GetAlarmRecord
    door_api_set_card_permission: /SetCardPermission
    door_api_session_id: SessionId=
    door_api_begin_time: BeginTime=
    door_api_end_time: EndTime=
    door_api_time_period: TimePeriod=
    door_api_card_permission: CardPermission=
