security:
    encoders:
        Sandbox\ClientApiBundle\Entity\User\ClientUserLogin: plaintext
        Sandbox\ClientApiBundle\Entity\Auth\ClientApiAuth: plaintext
        Sandbox\AdminApiBundle\Entity\Admin\AdminUserLogin: plaintext
        Sandbox\AdminApiBundle\Entity\Auth\AdminApiAuth: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_USER:        ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN_API:   ROLE_ADMIN_API
        ROLE_CLIENT_API:  ROLE_CLIENT_API

    providers:
        chain_provider:
            chain:
                providers: [userEmail, userPhoneNumber, clientApi, adminUser, adminApi]
        userEmail:
            entity:
                class: Sandbox\ClientApiBundle\Entity\User\ClientUserLogin
                property: email
        userPhoneNumber:
            entity:
                class: Sandbox\ClientApiBundle\Entity\User\ClientUserLogin
                property: phoneNumber
        clientApi:
            entity:
                class: Sandbox\ClientApiBundle\Entity\Auth\ClientApiAuth
                property: token
        adminUser:
            entity:
                class: Sandbox\AdminApiBundle\Entity\Admin\AdminUserLogin
                property: username
        adminApi:
            entity:
                class: Sandbox\AdminApiBundle\Entity\Auth\AdminApiAuth
                property: token

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            http_basic: ~
            stateless:  true

    access_control:
        - { path: ^/client/user/register/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/register/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/password/forget/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/password/forget/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/password/forget/reset$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/login$, role: ROLE_USER }
        - { path: ^/client, role: ROLE_CLIENT_API }
        - { path: ^/admin/user/login$, role: ROLE_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN_API }

