security:
    encoders:
        Sandbox\ClientApiBundle\Entity\User\ClientUserLogin: plaintext
        Sandbox\ClientApiBundle\Entity\Auth\ClientApiAuth: plaintext
        Sandbox\AdminApiBundle\Entity\Admin\AdminUserLogin: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_USER:        ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [userEmail, userPhoneNumber, clientApi, adminUser]
        userEmail:
            entity:
                class: Sandbox\ClientApiBundle\Entity\User\ClientUserLogin
                property: email
        userPhoneNumber:
            entity:
                class: Sandbox\ClientApiBundle\Entity\User\ClientUserLogin
                property: phoneNumber
        clientApi:
            entity:
                class: Sandbox\ClientApiBundle\Entity\Auth\ClientApiAuth
                # it's done like that because token is the only things
                # which is unique in this table
                property: token
        adminUser:
            entity:
                class: Sandbox\AdminApiBundle\Entity\Admin\AdminUserLogin
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            http_basic: ~
            stateless:  true

    access_control:
        - { path: ^/client/user/register/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/register/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/password/forget/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/password/forget/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/password/forget/reset$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_ADMIN }

