security:
    encoders:
        Sandbox\ApiBundle\Entity\User\User: plaintext
        Sandbox\ClientApiBundle\Entity\Auth\ClientApiAuth: plaintext
    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_CLIENT_API:  ROLE_CLIENT_API

    providers:
        chain_provider:
            chain:
                providers: [clientApi, userPhone, userEmail]
        clientApi:
            entity:
                class: Sandbox\ClientApiBundle\Entity\Auth\ClientApiAuth
                property: token
        userPhone:
            entity:
                class: Sandbox\ApiBundle\Entity\User\User
                property: phone
        userEmail:
            entity:
                class: Sandbox\ApiBundle\Entity\User\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        phone_code:
            pattern: ^/phonecode
            security: false
            methods: [GET]

        admin_dashboard_orders_export:
            pattern: ^/admin/dashboard/orders/export
            security: false
            methods: [GET]

        rooms_types:
            pattern: ^/rooms/types
            security: false
            methods: [GET]

        client_refresh_token_login:
            pattern: ^/client/auth/refresh
            security: false
            methods: [POST]

        shop_admin_orders_export:
            pattern: ^/shop/admin/orders/export
            security: false
            methods: [GET]

        admin_auth_login:
            pattern: ^/admin/auth/login
            security: false
            methods: [POST]

        client_user_register_submit:
            pattern: ^/client/user/register/submit
            security: false
            methods: [POST]

        client_user_register_verify:
            pattern: ^/client/user/register/verify
            security: false
            methods: [POST]

        client_user_password_forget_submit:
            pattern: ^/client/user/password/forget/submit
            security: false
            methods: [POST]

        client_user_password_forget_verify:
            pattern: ^/client/user/password/forget/verify
            security: false
            methods: [POST]

        client_user_password_forget_reset:
            pattern: ^/client/user/password/forget/reset
            security: false
            methods: [POST]

        client_payment_webhooks:
            pattern: ^/client/payment/webhooks
            security: false
            methods: [POST]

        client_banners:
            pattern: ^/client/banners
            security: false
            methods: [GET]

        client_advertising:
            pattern: ^/client/advertising
            security: false
            methods: [GET]

        client_news:
            pattern: ^/client/news
            security: false
            methods: [GET]

        client_auth_token:
            pattern: ^/client/auth/token$
            security: false

        client_thirdparty_oauth_login:
            pattern: ^/client/thirdparty/oauth/login$
            security: false

        sales_admin_events_orders_export:
            pattern: ^/sales/admin/events/orders/export$
            security: false

        sales_admin_orders_export:
            pattern: ^/sales/admin/orders/export$
            security: false

        admin_shop_orders_export:
            pattern: ^/admin/shop/orders/export$
            security: false

        admin_orders_export:
            pattern: ^/admin/orders/export$
            security: false

        admin_events_orders_export:
            pattern: ^/admin/events/orders/export$
            security: false

        admin_payment_refund:
            pattern: ^/admin/payment/refund$
            security: false

        user_background_attachments:
            pattern: ^/user/background/attachments$
            security: false

        user_avatar_attachments:
            pattern: ^/user/avatar/attachments$
            security: false

        client_evaluation:
            pattern: ^/client/evaluations$
            security: false
            methods: [GET]

        sales_admin_finance_summary_export:
            pattern: ^/sales/admin/finance/summary/export$
            security: false
            methods: [GET]

        admin_finance_cash_flow_export:
            pattern: ^/admin/finance/cash_flow/export$
            security: false
            methods: [GET]

        client_user_check:
            pattern: ^/client/auth/user_check$
            security: false
            methods: [POST]

        main:
            pattern: ^/
            anonymous: true
            http_basic: ~
            stateless:  true

    access_control:
        - { path: ^/admin/leases/export_to_pdf, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET]}
        - { path: ^/sales/admin/leases/export_to_pdf, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET]}
        - { path: ^/client/evaluations/check_my$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/evaluations$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/phonecode, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/admin/finance/export$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/rooms/types$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/auth/refresh, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/auth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/client/user/share$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/shop/admin/orders/export$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/admin/auth/check_code$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/admin/auth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/client/user/register/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/client/user/register/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/client/user/password/forget/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/client/user/password/forget/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/client/user/password/forget/reset$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/client/payment/webhooks$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/client/shops, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/shops/orders, role: ROLE_CLIENT_API}
        - { path: ^/client/banners, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/advertising, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/news, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/companies, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/members, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/user/profile, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/products, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/feeds, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/events, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/auth/token$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/thirdparty/oauth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/thirdparty/auth$, role: ROLE_USER }
        - { path: ^/client, role: ROLE_CLIENT_API }
        - { path: ^/sales/admin/events/orders/export$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sales/admin/orders/export$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sales, role: ROLE_CLIENT_API }
        - { path: ^/shop, role: ROLE_CLIENT_API }
        - { path: ^/admin/shop/orders/export$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/orders/export$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/events/orders/export$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/payment/refund$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_CLIENT_API }
        - { path: ^/user/background/attachments$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/avatar/attachments$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/openserver/client/auth/login$, role: ROLE_USER }
        - { path: ^/plugins/fileServer/fileservice, roles: ROLE_CLIENT_API }