security:
    encoders:
        Sandbox\ApiBundle\Entity\User\User: plaintext
        Sandbox\ClientApiBundle\Entity\Auth\ClientApiAuth: plaintext
        Sandbox\AdminApiBundle\Entity\Auth\AdminApiAuth: plaintext
        Sandbox\SalesApiBundle\Entity\Auth\SalesAdminApiAuth: plaintext
        Sandbox\AdminShopApiBundle\Entity\Auth\ShopAdminApiAuth: plaintext
    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_SALES_ADMIN_API: ROLE_SALES_ADMIN_API
        ROLE_SHOP_ADMIN_API: ROLE_SHOP_ADMIN_API
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN_API:   ROLE_ADMIN_API
        ROLE_CLIENT_API:  ROLE_CLIENT_API

    providers:
        chain_provider:
            chain:
                providers: [userEmail, userPhone, clientApi, adminApi, salesAdminApi, shopAdminApi]
        userEmail:
            entity:
                class: Sandbox\ApiBundle\Entity\User\User
                property: email
        userPhone:
            entity:
                class: Sandbox\ApiBundle\Entity\User\User
                property: phone
        clientApi:
            entity:
                class: Sandbox\ClientApiBundle\Entity\Auth\ClientApiAuth
                property: token
        adminApi:
            entity:
                class: Sandbox\AdminApiBundle\Entity\Auth\AdminApiAuth
                property: token
        salesAdminApi:
            entity:
                class: Sandbox\SalesApiBundle\Entity\Auth\SalesAdminApiAuth
                property: token
        shopAdminApi:
            entity:
                class: Sandbox\AdminShopApiBundle\Entity\Auth\ShopAdminApiAuth
                property: token

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            http_basic: ~
            stateless:  true

    access_control:
        - { path: ^/admin/auth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sales/admin/auth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/shop/admin/auth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/register/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/register/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/password/forget/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/password/forget/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/user/password/forget/reset$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/payment/webhooks$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/banners, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/news, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/companies, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/members, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/user/profile, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/products, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/feeds, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/events, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/client/auth/token$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/auth/login$, role: ROLE_USER }
        - { path: ^/client/thirdparty/oauth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/thirdparty/auth$, role: ROLE_USER }
        - { path: ^/client, role: ROLE_CLIENT_API }
        - { path: ^/admin/orders/export$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/payment/refund$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN_API }
        - { path: ^/user/background/attachments$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/avatar/attachments$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sales, role: ROLE_SALES_ADMIN_API }
        - { path: ^/shop, role: ROLE_SHOP_ADMIN_API }

