security:
    encoders:
        EZLinx\ApiBundle\Entity\UserAuth: plaintext
        EZLinx\ApiBundle\Entity\ValidApiUser: plaintext
        EZLinx\ApiBundle\Entity\ExternalEntity: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_EXTERNAL:    ROLE_EXTERNAL

    providers:
        chain_provider:
            chain:
                providers: [email, phone, api, external]
        email:
            entity:
                class: Sandbox\ApiBundle\Entity\UserAuth
                property: email
        phone:
            entity:
                class: Sandbox\ApiBundle\Entity\UserAuth
                property: phonenum
        api:
            entity:
                class: Sandbox\ApiBundle\Entity\ValidApiUser
                # it's done like that because secretDigest is the only things
                # which is unique in this table
                property: secretdigest
        external:
            entity:
                class: Sandbox\ApiBundle\Entity\ExternalEntity
                property: openid

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            http_basic: ~
            stateless:  true

    access_control:
        - { path: ^/register/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/invite, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/forget/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/forget/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/forget/reset$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/external/chat/message$, role: ROLE_EXTERNAL }
        - { path: ^/external/user/validation$, role: ROLE_EXTERNAL }
        - { path: ^/, role: ROLE_USER }

