security:
    encoders:
        Sandbox\ClientApiBundle\Entity\User\ClientUserLogin: plaintext
        Sandbox\ApiBundle\Entity\Auth\ValidApiUser: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_EXTERNAL:    ROLE_EXTERNAL

    providers:
        chain_provider:
            chain:
                providers: [userEmail, userPhoneNumber, api]
        userEmail:
            entity:
                class: Sandbox\ClientApiBundle\Entity\User\ClientUserLogin
                property: email
        userPhoneNumber:
            entity:
                class: Sandbox\ClientApiBundle\Entity\User\ClientUserLogin
                property: phoneNumber
        api:
            entity:
                class: Sandbox\ApiBundle\Entity\Auth\ValidApiUser
                # it's done like that because secretDigest is the only things
                # which is unique in this table
                property: secretdigest

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            http_basic: ~
            stateless:  true

    access_control:
        - { path: ^/register/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/invite, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/forget/submit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/forget/verify$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/forget/reset$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

