<?php

namespace Sandbox\ApiBundle\Repository\Menu;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    /**
     * @param $component
     * @param $platform
     *
     * @return array
     */
    public function getAllMenuVersion(
        $component,
        $platform
    ) {
        $query = $this->createQueryBuilder('m')
            ->select('
                m.id,
                m.minVersion,
                m.maxVersion
            ')
            ->where('m.component = :component')
            ->andWhere('m.platform = :platform')
            ->setParameter('component', $component)
            ->setParameter('platform', $platform);

        return $query->getQuery()->getResult();
    }
}
