sandbox_client_property_api_orders_product:
    resource: "@SandboxClientPropertyApiBundle/Controller/Order/ClientOrderController.php"
    type:     annotation
    prefix:   /

sandbox_client_property_api_orders_event:
    resource: "@SandboxClientPropertyApiBundle/Controller/Order/ClientEventOrderController.php"
    type:     annotation
    prefix:   /