# Shop /shop/admin/shops
sandbox_admin_shop_api_shops:
    resource: "@SandboxAdminShopApiBundle/Controller/Shop/AdminShopController.php"
    type:     annotation
    prefix:   /admin

# ShopMenu /shop/admin/shops/menu
sandbox_shop_admin_api_shops_menu:
    resource: "@SandboxAdminShopApiBundle/Controller/Shop/AdminShopMenuController.php"
    type:     annotation
    prefix:   /admin

# Spec /shop/admin/shops/spec
sandbox_shop_admin_api_shops_spec:
    resource: "@SandboxAdminShopApiBundle/Controller/Shop/AdminShopSpecController.php"
    type:     annotation
    prefix:   /admin

# Product /shop/admin/shops/product
sandbox_shop_admin_api_shops_product:
    resource: "@SandboxAdminShopApiBundle/Controller/Shop/AdminShopProductController.php"
    type:     annotation
    prefix:   /admin