# Example
#sandbox_client_api_feed:
#    resource: "@SandboxClientApiBundle/Controller/Feed/ClientFeedController.php"
#    type:     annotation
#    prefix:   /

commnue_admin_default_controller:
    resource: "@CommnueAdminApiBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

commnue_admin_event_hot_controller:
    resource: "@CommnueAdminApiBundle/Controller/Event/AdminEventHotController.php"
    type:     annotation
    prefix:   /

commnue_admin_advertising_banner_controller:
    resource: "@CommnueAdminApiBundle/Controller/Advertising/AdminAdvertisingBannerController.php"
    type:     annotation
    prefix:   /

commnue_admin_advertising_middle_controller:
    resource: "@CommnueAdminApiBundle/Controller/Advertising/AdminAdvertisingMiddleController.php"
    type:     annotation
    prefix:   /

commnue_admin_advertising_micro_controller:
    resource: "@CommnueAdminApiBundle/Controller/Advertising/AdminAdvertisingMicroController.php"
    type:     annotation
    prefix:   /

commnue_admin_advertising_screen_controller:
    resource: "@CommnueAdminApiBundle/Controller/Advertising/AdminAdvertisingScreenController.php"
    type:     annotation
    prefix:   /

commnue_admin_advertising_material_controller:
    resource: "@CommnueAdminApiBundle/Controller/Advertising/AdminMaterialController.php"
    type:     annotation
    prefix:   /

commnue_admin_user:
    resource: "@CommnueAdminApiBundle/Controller/User/AdminUserController.php"
    type:     annotation
    prefix:   /

commue_admin_user_auth_tags:
    resource: "@CommnueAdminApiBundle/Controller/User/AdminUserAuthenticationTagsController.php"
    type:     annotation
    prefix:   /

commnue_admin_community_controller:
    resource: "@CommnueAdminApiBundle/Controller/Community/AdminCommunityController.php"
    type:     annotation
    prefix:   /

commnue_admin_dashboard_users_data:
    resource: "@CommnueAdminApiBundle/Controller/Dashboard/AdminDashboardController.php"
    type:     annotation
    prefix:   /

commnue_admin_expert_field:
    resource: "@CommnueAdminApiBundle/Controller/Expert/AdminExpertFieldController.php"
    type:     annotation
    prefix:   /

commnue_admin_experts:
    resource: "@CommnueAdminApiBundle/Controller/Expert/AdminExpertController.php"
    type:     annotation
    prefix:   /