# Example
#sandbox_client_api_feed:
#    resource: "@SandboxClientApiBundle/Controller/Feed/ClientFeedController.php"
#    type:     annotation
#    prefix:   /

commnue_admin_default_controller:
    resource: "@CommnueAdminApiBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

commnue_admin_api_Advertising_banner:
    resource: "@CommnueAdminApiBundle/Controller/Avertising/AdminAdvertisingBannerController.php"
    type:     annotation
    prefix:   /

commnue_admin_api_Advertising_middle:
    resource: "@CommnueAdminApiBundle/Controller/Avertising/AdminAdvertisingMiddleController.php"
    type:     annotation
    prefix:   /

commnue_admin_api_Advertising_micro:
    resource: "@CommnueAdminApiBundle/Controller/Avertising/AdminAdvertisingMicroController.php"
    type:     annotation
    prefix:   /