# Example
#sandbox_client_api_feed:
#    resource: "@SandboxClientApiBundle/Controller/Feed/ClientFeedController.php"
#    type:     annotation
#    prefix:   /

commnue_admin_default_controller:
    resource: "@SandboxCommnueAdminApiBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
commnue_admin_api_advertising_banner:
    resource: "@SandboxCommnueAdminApiBundle/Controller/Advertising/AdminAdvertisingBannerController.php"
    type:     annotation
    prefix:   /
commnue_admin_api_advertising_middle:
    resource: "@SandboxCommnueAdminApiBundle/Controller/Advertising/AdminAdvertisingMiddleController.php"
    type:     annotation
    prefix:   /
#commnue_admin_api_advertising_micro:
#    resource: "@SandboxCommnueAdminApiBundle/Controller/Advertising/AdminAdvertisingMicroController.php"
#    type:     annotation
#    prefix:   /
commnue_admin_api_advertising_material:
    resource: "@SandboxCommnueAdminApiBundle/Controller/Advertising/AdminMaterialController.php"
    type:     annotation
    prefix:   /