CREATE TABLE `UserProfile` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userId` int(11) NOT NULL,
  `name` varchar(64) NOT NULL,
  `jobTitle` varchar(64) DEFAULT NULL,
  `gender` enum('other','female','male') DEFAULT NULL,
  `dateOfBirth` date DEFAULT NULL,
  `phone` varchar(64) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `aboutMe` text,
  `skill` text,
  `sinaWeibo` varchar(128) DEFAULT NULL,
  `tencentWeibo` varchar(128) DEFAULT NULL,
  `facebook` varchar(128) DEFAULT NULL,
  `linkedin` varchar(128) DEFAULT NULL,
  `buildingId` int(11) DEFAULT NULL,
  `creationDate` datetime NOT NULL,
  `modificationDate` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_UserProfile_userId` (`userId`),
  CONSTRAINT `fk_UserProfile_userId` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  KEY `fk_UserProfile_buildingId_idx` (`buildingId`),
  CONSTRAINT `fk_UserProfile_buildingId` FOREIGN KEY (`buildingId`) REFERENCES `RoomBuilding` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
