CREATE TABLE `UserPhoneCode` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cnName` VARCHAR(255) NOT NULL,
  `enName` VARCHAR(255) NOT NULL,
  `code` VARCHAR(122) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("阿富汗","Afghanistan","+93");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("阿拉斯加","Alaska","+1907");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("阿尔巴尼亚","Albania","+355");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("阿尔及利亚","Algeria","+213");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("美国","America","+1");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("安道尔","Andorra","+376");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("安哥拉","Angola","+244");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("安圭拉岛","Anguilla I.","+1264");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("安提瓜和巴布达","Antigua and Barbuda","+1268");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("阿根廷","Argentina","+54");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("亚美尼亚","Armenia","+374");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("阿鲁巴岛","Aruba I.","+297");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("阿森松","Ascension","+247");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("澳大利亚","Australia","+61");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("奥地利","Austria","+43");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("阿塞拜疆","Azerbaijan","+994");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("巴林","Bahrain","+973");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("孟加拉国","Bangladesh","+880");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("巴巴多斯","Barbados","+1246");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("白俄罗斯","Belarus","+375");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("比利时","Belgium","+32");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("伯利兹","Belize","+501");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("贝宁","Benin","+229");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("百慕大群岛","Bermuda Is.","+1441");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("不丹","Bhutan","+975");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("玻利维亚","Bolivia","+591");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("波斯尼亚和黑塞哥维那","Bosnia And Herzegovina","+387");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("博茨瓦纳","Botswana","+267");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("巴西","Brazil","+55");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("保加利亚","Bulgaria","+359");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("布基纳法索","Burkinafaso","+226");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("布隆迪","Burundi","+257");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("喀麦隆","Cameroon","+237");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("加拿大","Canada","+1");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("加那利群岛","Canaries Is.","+34");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("佛得角","Cape Verde","+238");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("开曼群岛","Cayman Is.","+1345");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("中非","Central Africa","+236");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("乍得","Chad","+235");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("中华人民共和国","China","+86");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("智利","Chile","+56");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("圣诞岛","Christmas I.","+61 9164 ");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("科科斯岛","Cocos I.","+61 9162 ");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("哥伦比亚","Colombia","+57");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("巴哈马国","Commonwealth of The Bahamas","+1809");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("多米尼克国","Commonwealth of dominica","+1809");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("科摩罗","Comoro","+269");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("刚果","Congo","+242");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("科克群岛","Cook IS.","+682");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("哥斯达黎加","Costa Rica","+506");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("克罗地亚","Croatian","+383 385 ");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("古巴","Cuba","+53");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("塞浦路斯","Cyprus","+357");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("捷克","Czech","+420");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("丹麦","Denmark","+45");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("迪戈加西亚岛","Diego Garcia I.","+246");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("吉布提","Djibouti","+253");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("多米尼加共和国","Dominican Rep.","+1809");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("厄瓜多尔","Ecuador","+593");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("埃及","Egypt","+20");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("萨尔瓦多","El Salvador","+503");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("赤道几内亚","Equatorial Guinea","+240");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("厄立特里亚","Eritrea","+291");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("爱沙尼亚","Estonia","+372");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("埃塞俄比亚","Ethiopia","+251");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("福克兰群岛","Falkland Is.","+500");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("法罗群岛","Faroe Is.","+298");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("斐济","Fiji","+679");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("芬兰","Finland","+358");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("法国","France","+33");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("法属圭亚那","French Guiana","+594");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("法属波里尼西亚","French Polynesia","+689");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("加蓬","Gabon","+241");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("冈比亚","Gambia","+220");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("格鲁吉亚","Georgia","+995");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("德国","Germany","+49");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("加纳","Ghana","+233");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("直布罗陀","Gibraltar","+350");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("希腊","Greece","+30");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("格陵兰岛","Greenland","+299");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("格林纳达","Grenada","+1809");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("瓜德罗普岛","Guadeloupe I.","+590");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("关岛","Guam","+671");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("危地马拉","Guatemala","+502");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("几内亚","Guinea","+224");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("几内亚比绍","Guinea-bissau","+245");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("圭亚那","Guyana","+592");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("海地","Haiti","+509");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("夏威夷","Hawaii","+1808");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("洪都拉斯","Honduras","+504");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("匈牙利","HunGary","+36");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("冰岛","Iceland","+354");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("印度","India","+91");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("印度尼西亚","Indonesia","+62");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("伊郎","Iran","+98");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("伊拉克","Iraq","+964");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("爱尔兰","Ireland","+353");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("以色列","Israel","+972");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("意大利","Italy","+39");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("科特迪瓦","Ivory Coast","+225");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("牙买加","Jamaica","+1876");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("日本","Japan","+81");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("约旦","Jordan","+962");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("柬埔塞","Kampuchea","+855");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("哈萨克斯坦","Kazakhstan","+7");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("肯尼亚","Kenya","+254");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("基里巴斯","Kiribati","+686");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("朝鲜","North Korea","+850");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("韩国","South Korea","+82");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("科威特","Kuwait","+965");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("吉尔吉斯斯坦","Kyrgyzstan","+7");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("老挝","Laos","+856");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("拉脱维亚","Latvia","+371");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("黎巴嫩","Lebanon","+961");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("莱索托","Lesotho","+266");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("利比里亚","Liberia","+231");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("利比亚","Libya","+218");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("列支敦士登","Liechtenstein","+41 75 ");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("立陶宛","Lithuania","+370");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("卢森堡","Luxembourg","+352");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马其顿","Macedonia","+389");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马达加斯加","Madagascar","+261");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马拉维","Malawi","+265");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马来西亚","Malaysia","+60");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马尔代夫","Maldive","+960");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马里","Mali","+223");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马耳他","Malta","+356");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马里亚纳群岛","Mariana Is.","+670");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马绍尔群岛","Marshall Is.","+692");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马提尼克","Martinique","+596");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("毛里塔尼亚","Mauritania","+222");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("毛里求斯","Mauritius","+230");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("马约特岛","Mayotte I.","+269");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("墨西哥","Mexico","+52");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("密克罗尼西亚","Micronesia","+691");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("中途岛","Midway I.","+1808");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("摩尔多瓦","Moldova","+373");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("摩纳哥","Monaco","+377");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("蒙古","Mongolia","+976");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("蒙特塞拉特岛","Montserrat I.","+1664");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("摩洛哥","Morocco","+212");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("莫桑比克","Mozambique","+258");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("缅甸","Myanmar","+95");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("纳米比亚","Namibia","+264");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("瑙鲁","Nauru","+674");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("尼泊尔","Nepal","+977");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("荷兰","Netherlands","+31");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("荷属安的列斯群岛","Netherlandsantilles Is.","+599");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("新喀里多尼亚群岛","New Caledonia Is.","+687");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("新西兰","New Zealand","+64");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("尼加拉瓜","Nicaragua","+505");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("尼日尔","Niger","+227");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("尼日利亚","Nigeria","+234");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("纽埃岛","Niue I.","+683");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("诺福克岛","Norfolk I,","+6723");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("挪威","Norway","+47");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("阿曼","Oman","+968");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("帕劳","Palau","+680");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("巴拿马","Panama","+507");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("巴布亚新几内亚","Papua New Guinea","+675");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("巴拉圭","Paraguay","+595");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("秘鲁","Peru","+51");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("菲律宾","Philippines","+63");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("波兰","Poland","+48");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("葡萄牙","Portugal","+351");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("巴基斯坦","Pskistan","+92");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("波多黎各","Puerto Rico","+1787");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("卡塔尔","Qatar","+974");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("留尼汪岛","Reunion I.","+262");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("罗马尼亚","Rumania","+40");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("俄罗斯","Russia","+7");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("卢旺达","Rwanda","+250");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("东萨摩亚","Samoa ,Eastern","+684");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("西萨摩亚","Samoa ,Western","+685");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("圣马力诺","San.Marino","+378");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("圣皮埃尔岛及密克隆岛","San.Pierre And Miquelon I.","+508");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("圣多美和普林西比","San.Tome And Principe","+239");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("沙特阿拉伯","Saudi Arabia","+966");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("塞内加尔","Senegal","+221");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("塞舌尔","Seychelles","+248");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("新加坡","Singapore","+65");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("斯洛伐克","Slovak","+421");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("斯洛文尼亚","Slovenia","+386");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("所罗门群岛","Solomon Is.","+677");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("索马里","Somali","+252");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("南非","South Africa","+27");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("西班牙","Spain","+34");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("斯里兰卡","Sri Lanka","+94");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("圣克里斯托弗和尼维斯","St.Christopher and Nevis","+1809");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("圣赫勒拿","St.Helena","+290");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("圣卢西亚","St.Lucia","+1758");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("圣文森特岛","St.Vincent I.","+1784");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("苏丹","Sudan","+249");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("苏里南","Suriname","+597");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("斯威士兰","Swaziland","+268");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("瑞典","Sweden","+46");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("瑞士","Switzerland","+41");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("叙利亚","Syria","+963");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("塔吉克斯坦","Tajikistan","+7");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("坦桑尼亚","Tanzania","+255");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("泰国","Thailand","+66");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("阿拉伯联合酋长国","The United Arab Emirates","+971");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("多哥","Togo","+228");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("托克劳群岛","Tokelau Is.","+690");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("汤加","Tonga","+676");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("特立尼达和多巴哥","Trinidad and Tobago","+1809");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("突尼斯","Tunisia","+216");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("土耳其","Turkey","+90");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("土库曼斯坦","Turkmenistan","+993");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("特克斯和凯科斯群岛","Turks and Caicos Is.","+1809");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("图瓦卢","Tuvalu","+688");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("乌干达","Uganda","+256");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("乌克兰","Ukraine","+380");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("英国","United Kingdom","+44");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("乌拉圭","Uruguay","+598");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("乌兹别克斯坦","Uzbekistan","+7");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("瓦努阿图","Vanuatu","+678");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("梵蒂冈","Vatican","+379");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("委内瑞拉","Venezuela","+58");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("越南","Vietnam","+84");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("维尔京群岛","Virgin Is.","+1809");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("维尔京群岛和圣罗克伊","Virgin Is. and St.Croix I.","+1809");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("威克岛","Wake I.","+1808");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("瓦里斯和富士那群岛","Wallis And Futuna Is.","+681");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("西撒哈拉","Western sahara","+967");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("也门","Yemen","+967");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("南斯拉夫","Yugoslavia","+381");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("扎伊尔","Zaire","+243");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("赞比亚","Zambia","+260");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("桑给巴尔","Zanzibar","+259");
INSERT INTO UserPhoneCode(`cnName`,`enName`,`code`) VALUES("津巴布韦","Zimbabwe","+263");